name: frontend
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.7.0
  web_socket_channel: ^3.0.1
  flutter_form_builder: ^9.5.0
  hydrated_bloc: ^9.1.5
  json_serializable: ^6.8.0
  get_it: ^8.0.1
  go_router: ^14.3.0  
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
