// Mocks generated by Mockito 5.4.4 from annotations
// in frontend/test/presentation/screens/car_list_test/car_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:frontend/domain/usecases/usecases.dart' as _i2;
import 'package:frontend/presentation/presenters/car/car_bloc.dart' as _i4;
import 'package:frontend/presentation/presenters/car/car_event.dart' as _i6;
import 'package:frontend/presentation/presenters/car/car_state.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetCars_0 extends _i1.SmartFake implements _i2.GetCars {
  _FakeGetCars_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateCar_1 extends _i1.SmartFake implements _i2.CreateCar {
  _FakeCreateCar_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateCar_2 extends _i1.SmartFake implements _i2.UpdateCar {
  _FakeUpdateCar_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteCar_3 extends _i1.SmartFake implements _i2.DeleteCar {
  _FakeDeleteCar_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClearToken_4 extends _i1.SmartFake implements _i2.ClearToken {
  _FakeClearToken_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCarState_5 extends _i1.SmartFake implements _i3.CarState {
  _FakeCarState_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CarBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarBloc extends _i1.Mock implements _i4.CarBloc {
  MockCarBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetCars get getCars => (super.noSuchMethod(
        Invocation.getter(#getCars),
        returnValue: _FakeGetCars_0(
          this,
          Invocation.getter(#getCars),
        ),
      ) as _i2.GetCars);

  @override
  _i2.CreateCar get createCar => (super.noSuchMethod(
        Invocation.getter(#createCar),
        returnValue: _FakeCreateCar_1(
          this,
          Invocation.getter(#createCar),
        ),
      ) as _i2.CreateCar);

  @override
  _i2.UpdateCar get updateCar => (super.noSuchMethod(
        Invocation.getter(#updateCar),
        returnValue: _FakeUpdateCar_2(
          this,
          Invocation.getter(#updateCar),
        ),
      ) as _i2.UpdateCar);

  @override
  _i2.DeleteCar get deleteCar => (super.noSuchMethod(
        Invocation.getter(#deleteCar),
        returnValue: _FakeDeleteCar_3(
          this,
          Invocation.getter(#deleteCar),
        ),
      ) as _i2.DeleteCar);

  @override
  _i2.ClearToken get clearToken => (super.noSuchMethod(
        Invocation.getter(#clearToken),
        returnValue: _FakeClearToken_4(
          this,
          Invocation.getter(#clearToken),
        ),
      ) as _i2.ClearToken);

  @override
  bool get isFormValid => (super.noSuchMethod(
        Invocation.getter(#isFormValid),
        returnValue: false,
      ) as bool);

  @override
  _i3.CarState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeCarState_5(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.CarState);

  @override
  _i5.Stream<_i3.CarState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.CarState>.empty(),
      ) as _i5.Stream<_i3.CarState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i6.CarEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.CarEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.CarState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.CarEvent>(
    _i7.EventHandler<E, _i3.CarState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i7.Transition<_i6.CarEvent, _i3.CarState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void onChange(_i7.Change<_i3.CarState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
