// Mocks generated by Mockito 5.4.4 from annotations
// in frontend/test/presentation/presenters/car/car_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:frontend/domain/entities/entities.dart' as _i3;
import 'package:frontend/domain/repositories/repositories.dart' as _i2;
import 'package:frontend/domain/usecases/clear_token.dart' as _i9;
import 'package:frontend/domain/usecases/create_car.dart' as _i6;
import 'package:frontend/domain/usecases/delete_car.dart' as _i8;
import 'package:frontend/domain/usecases/get_cars.dart' as _i4;
import 'package:frontend/domain/usecases/update_car.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCarRepository_0 extends _i1.SmartFake implements _i2.CarRepository {
  _FakeCarRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCar_1 extends _i1.SmartFake implements _i3.Car {
  _FakeCar_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTokenRepository_2 extends _i1.SmartFake
    implements _i2.TokenRepository {
  _FakeTokenRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCars].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCars extends _i1.Mock implements _i4.GetCars {
  MockGetCars() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CarRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCarRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CarRepository);

  @override
  _i5.Future<List<_i3.Car>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Car>>.value(<_i3.Car>[]),
      ) as _i5.Future<List<_i3.Car>>);
}

/// A class which mocks [CreateCar].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCar extends _i1.Mock implements _i6.CreateCar {
  MockCreateCar() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CarRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCarRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CarRepository);

  @override
  _i5.Future<_i3.Car> call(
    String? name,
    String? model,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            name,
            model,
          ],
        ),
        returnValue: _i5.Future<_i3.Car>.value(_FakeCar_1(
          this,
          Invocation.method(
            #call,
            [
              name,
              model,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Car>);
}

/// A class which mocks [UpdateCar].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateCar extends _i1.Mock implements _i7.UpdateCar {
  MockUpdateCar() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CarRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCarRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CarRepository);

  @override
  _i5.Future<void> call(
    int? id,
    String? name,
    String? model,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            id,
            name,
            model,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [DeleteCar].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCar extends _i1.Mock implements _i8.DeleteCar {
  MockDeleteCar() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CarRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCarRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CarRepository);

  @override
  _i5.Future<void> call(int? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ClearToken].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearToken extends _i1.Mock implements _i9.ClearToken {
  MockClearToken() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TokenRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTokenRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TokenRepository);

  @override
  _i5.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
